services:
  db:
    image: postgres:15
    container_name: media_db
    restart: always
    environment:
      POSTGRES_DB: media_db
      POSTGRES_USER: media_user
      POSTGRES_PASSWORD: media_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: media_api
    build:
      context: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/media_db
      SPRING_DATASOURCE_USERNAME: media_user
      SPRING_DATASOURCE_PASSWORD: media_pass
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pgdata:
