# Server
spring.application.name=media-streaming-api
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/media_db
spring.datasource.username=media_user
spring.datasource.password=media_pass

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Video Path
file.folder.path=videos
